services:
  sql-mcp-server:
    build: .
    container_name: sql-mcp-server
    ports:
      - 8000:8000
    env_file: .env
    # Restart policy
    restart: unless-stopped

  # Optional: SQL Server service for local development
  # Uncomment the section below if you want to run SQL Server locally
  # sqlserver:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   container_name: sql-server
  #   environment:
  #     ACCEPT_EULA: "Y"
  #     SA_PASSWORD: "YourStrong@Passw0rd"
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - sqlserver_data:/var/opt/mssql
  #   restart: unless-stopped

# volumes:
#   sqlserver_data: